using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Robam_Sync.Models
{
    public class CRM_PartsReturnDetail
    {
        public int? orderId{get;set;}// 34078302,
        public string? orderNum{get;set;}// "JSTH202301050289",
        public int? orderTypeId {get;set;}// 212,
        public string? distributionChannels{get;set;}// null,
        public string? productCategory{get;set;}// null,
        public int? deptId {get;set;}// null,
        public string? salesRepresentative{get;set;}// null,
        public string? orderDate{get;set;}// null,
        public string? poNo{get;set;}// null,
        public string? currencyCode{get;set;}// null,
        public string? wholeDiscount{get;set;}// null,
        public decimal wholeDiscountAmount{get;set;}// null,
        public decimal taxSumAmount {get;set;}// null,
        public decimal sumAmount {get;set;}// 15,
        public string? customerConfirmTime{get;set;}// null,
        public string? pricingTime{get;set;}// null,
        public int? priceListId {get;set;}// null,
        public int? priceDiscountId {get;set;}// null,
        public string? deliveryTime{get;set;}// null,
        public string? deliveryPlace{get;set;}// null,
        public string? deliveryType{get;set;}// null,
        public string? transportType{get;set;}// "B",
        public string? transportRoute{get;set;}// null,
        public string? paymentTerm{get;set;}// null,
        public string? freightTerm{get;set;}// null,
        public string? commercialTerm{get;set;}// null,
        public string? sourceType{get;set;}// null,
        public int? sourceId {get;set;}// 6208515,
        public int? createdBy {get;set;}// 103,
        public string? creationDate{get;set;}// "2023-01-05",
        public int? lastUpdatedBy {get;set;}// 103,
        public string? lastUpdateDate{get;set;}// "2023-01-05",
        public string? remark{get;set;}// "APP技师配件退回",
        public int? orgId {get;set;}// 1,
        public int? customerAddressId {get;set;}// null,
        public int? customerId {get;set;}// 26532145,
        public string? isPriceIncludedTax{get;set;}// null,
        public string? versionNumber{get;set;}// null,
        public int? referenceId {get;set;}// null,
        public string? status{get;set;}// "C",
        public string? addressCode{get;set;}// null,
        public string? customerContact{get;set;}// null,
        public string? contactTel{get;set;}// null,
        public string? warehouseLocation{get;set;}// null,
        public string? countrysideFlag{get;set;}// null,
        public string? isInternalOrder{get;set;}// null,
        public string? isInternationalTrade{get;set;}// null,
        public string? isNeedUserinfo{get;set;}// "N",
        public string? priceIsForcedToConsult{get;set;}// null,
        public string? settlementMode{get;set;}// null,
        public string? sampleSalesFlag{get;set;}// null,
        public string? businessType{get;set;}// "B",
        public int? deliveryOrg {get;set;}// 20,
        public int? deliveryWarehouse {get;set;}// 70280329,
        public string? businessStatus{get;set;}// null,
        public string? returnsNum{get;set;}// null,
        public string? priceType{get;set;}// null,
        public string? customerAccess{get;set;}// null,
        public string? creditDeficiencyFlag{get;set;}// null,
        public string? notInSales{get;set;}// null,
        public string? noNeedCheckAmount{get;set;}// null,
        public string? noNeedInvoiceFlag{get;set;}// null,
        public string? invoiceMakeType{get;set;}// null,
        public string? employeeCode{get;set;}// null,
        public string? isRetainInvQty{get;set;}// null,
        public int? salesAreaId {get;set;}// 66820,
        public decimal goodsAmount {get;set;}// 15,
        public string? orderTypeName{get;set;}// "技师配件退回",
        public string? typeOfCreateNum{get;set;}// "A",
        public string? pointOfCreateNum{get;set;}// "B",
        public string? orgName{get;set;}// "老板电器账套",
        public string? deptName{get;set;}// null,
        public string? salesAreaName{get;set;}// "石家庄流巨家电销售有限公司",
        public string? customerCode{get;set;}// "JS-031130042",
        public string? customerName{get;set;}// "崔文星",
        public string? contact{get;set;}// null,
        public string? tel{get;set;}// null,
        public string? salesRepresentativeName{get;set;}// null,
        public string? createdName{get;set;}// "ROBAM_APP",
        public string? lastUpdatedName{get;set;}// "ROBAM_APP",
        public string? priceName{get;set;}// null,
        public string? discountName{get;set;}// null,
        public string? priceTerms{get;set;}// null,
        public string? paymentMethod{get;set;}// null,
        public string? returnReasonsName{get;set;}// null,
        public string? sourceCode{get;set;}// null,
        public string? routeName{get;set;}// null,
        public int? statusAndControlId {get;set;}// null,
        public string? controlStatus{get;set;}// "C",
        public string? deliveryFreeze{get;set;}// null,
        public string? invoiceFreeze{get;set;}// null,
        public string? emergencyDegree{get;set;}// null,
        public string? isDeferred{get;set;}// null,
        public string? isReturn{get;set;}// null,
        public string? returnReason{get;set;}// null,
        public string? haveArrears{get;set;}// null,
        public string? wholeSingleDelivery{get;set;}// null,
        public int? closedReasonId {get;set;}// null,
        public string? orderFreeze{get;set;}// null,
        public string? closedReasonName{get;set;}// null,
        public string? addressName{get;set;}// null,
        public string? deliveryWarehouseName{get;set;}// "崔文星-技师仓",
        public string? warehouseLocationName{get;set;}// null,
        public string? deliveryOrgName{get;set;}// "老板电器库存组织",
        public string? salesAssistantCode{get;set;}// null,
        public string? customerTypeName{get;set;}// "技师",
        public string? invLocationType{get;set;}// null,
        public string? transEntityNo{get;set;}// null,
        public string? dmdNum{get;set;}// null,
        public string? performanceAttribution{get;set;}// null,
        public string? performanceAttributionName{get;set;}// null,
        public string? companyPerformanceCode{get;set;}// null,
        public string? companyPerformanceName{get;set;}// null,
        public string? rebateFlag{get;set;}// null,
        public string? confirmType{get;set;}// null,
        public string? confirmTypeName{get;set;}// null,
        public int? salesProcessId {get;set;}// null,
        public string? salesProcessCode{get;set;}// null,
        public string? salesProcessName{get;set;}// null,
        public string? writeInvIfFlag{get;set;}// "Y",
        public string? writeTransIfFlag{get;set;}// null,
        public string? writeRaIfFlag{get;set;}// null,
        public string? writeSorFlag{get;set;}// null,
        public string? typeOfCreateNumName{get;set;}// "自动",
        public string? pointOfCreateNumName{get;set;}// "新增保存时",
        public string? invLocationTypeName{get;set;}// null,
        public string? lgMode{get;set;}// null,
        public string? lgModeName{get;set;}// null,
        public string? boFlag{get;set;}// null,
        public string? scFlag{get;set;}// null,
        public string? qpFlag{get;set;}// null,
        public string? soFlag{get;set;}// null,
        public string? sorFlag{get;set;}// null,
        public string? invExFlag{get;set;}// null,
        public string? transTaskFlag{get;set;}// null,
        public string? transEntityFlag{get;set;}// null,
        public string? invoicePoolFlag{get;set;}// null,
        public string? invoicePoolSource{get;set;}// null,
        public string? invoicePoolSourceName{get;set;}// null,
        public string? invoicePoolWritePoint{get;set;}// null,
        public string? invoicePoolWritePointName{get;set;}// null,
        public string? statusName{get;set;}// "审批通过",
        public string? sourceProperties{get;set;}// null,
        public string? sourceTypeName{get;set;}// null,
        public string? sourcePropertiesName{get;set;}// null,
        public string? businessTypeName{get;set;}// "退货",
        public string? fundControlMode{get;set;}// null,
        public string? fundControlModeName{get;set;}// null,
        public string? fundControlLevel{get;set;}// null,
        public string? fundControlLevelName{get;set;}// null,
        public string? transType{get;set;}// null,
        public string? transTypeName{get;set;}// null,
        public string? isReceiveInventory{get;set;}// "N",
        public int? receiveInventoryId {get;set;}// 70252904,
        public string? receiveInventoryName{get;set;}// "沧州仓库",
        public int? receiveLocationId {get;set;}// null,
        public string? receiveLocationName{get;set;}// null,
        public string? isBugetNode{get;set;}// null,
        public string? multiProductProcess{get;set;}// null,
        public string? multiProductProcessName{get;set;}// null,
        public string? isAllowedChange{get;set;}// null,
        public string? wfEditStatus{get;set;}// null,
        public int? productOrgId {get;set;}// 29,
        public string? productOrgName{get;set;}// "老板物料",
        public string? isCustomerUnrelated{get;set;}// null,
        public string? isStocking{get;set;}// null,
        public string? isInTransit{get;set;}// "Y",
        public string? receiveLocationType{get;set;}// null,
        public string? receiveLocationTypeName{get;set;}// null,
        public string? codeType{get;set;}// "JSTH",
        public int? exportAreaId {get;set;}// null,
        public string? exportAreaName{get;set;}// null,
        public int? inceptAreaId {get;set;}// null,
        public string? inceptAreaName{get;set;}// null,
        public string? fastOrdersFlag{get;set;}// null,
        public string? isLocationTypeLimit{get;set;}// "Y",
        public string? contactName{get;set;}// null,
        public string? storeCode{get;set;}// null,
        public string? storeName{get;set;}// null,
        public int? customerStoreId {get;set;}// null,
        public string? surplusAmount{get;set;}// null,
        public string? sourceOrderCode{get;set;}// null,
        public int? customerTypeId {get;set;}// 111,
        public string? deliveryWarehouseCode{get;set;}// "INV-031130042",
        public string? receiveInventoryCode{get;set;}// "sjzb003001",
        public int? policyHeaderId {get;set;}// null,
        public string? remarkPolicy{get;set;}// null,
        public int? relationOrderId {get;set;}// null,
        public int? blueOrderId {get;set;}// null,
        public string? redFlag{get;set;}// null,
        public int? administrationAreaId {get;set;}// null,
        public string? contactEmail{get;set;}// null,
        public string? freightStation{get;set;}// null,
        public string? freightStationLine{get;set;}// null,
        public int? goodsPoolId {get;set;}// 101,
        public string? exportFlag{get;set;}// null,
        public string? isPolicyFirst{get;set;}// null,
        public string? policyNo{get;set;}// null,
        public string? policyName{get;set;}// null,
        public string? goodsTypeName{get;set;}// "赊账额度池",
        public string? relationOrderNum{get;set;}// null,
        public string? blueOrderNum{get;set;}// null,
        public string? exportDate{get;set;}// null,
        public string? accountFlag{get;set;}// "N",
        public string? accountDate{get;set;}// null,
        public string? freightAddr{get;set;}// null,
        public string? accountBy{get;set;}// null,
        public string? exportBy{get;set;}// null,
        public string? isGroupByCategory{get;set;}// null,
        public string? exportFinishDate{get;set;}// null,
        public string? exportFinishFlag{get;set;}// null,
        public string? inceptAddress{get;set;}// null,
        public string? erpFlag{get;set;}// "N",
        public string? erpDate{get;set;}// null,
        public string? counterInch{get;set;}// null,
        public string? orderGroupByCategory{get;set;}// null,
        public string? printFlag{get;set;}// null,
        public string? printCount{get;set;}// null,
        public string? printBy{get;set;}// null,
        public string? printDate{get;set;}// null,
        public string? orderBusinessType{get;set;}// "B",
        public int? contractId {get;set;}// null,
        public string? contractCode{get;set;}// null,
        public string? brand{get;set;}// null,
        public string? despatchAdvice{get;set;}// null,
        public string? packingInstruction{get;set;}// null,
        public string? attachment{get;set;}// null,
        public int? billAddressId {get;set;}// null,
        public string? billAddress{get;set;}// null,
        public string? settlementAmount{get;set;}// null,
        public string? projectName{get;set;}// null,
        public string? branchApproval{get;set;}// 1,
        public string? branchApprovalName{get;set;}// "超级用户",
        public string? branchApprovalTime{get;set;}// "2023-01-05",
        public string? areaApprovalName{get;set;}// "超级用户",
        public string? areaApproval{get;set;}// null,
        public string? areaApprovalTime{get;set;}// null,
        public string? orderCommitTime{get;set;}// "2023-01-05",
        public string? erpErrInfo{get;set;}// null,
        public string? erpOrderNum{get;set;}// null,
        public int? description{get;set;}// 0,
        public string? cashCoupon{get;set;}// null,
        public string? rebateAmount{get;set;}// null,
        public string? feeAmount{get;set;}// null,
        public string? shopCode{get;set;}// null,
        public string? installAddress{get;set;}// null,
        public string? shopName{get;set;}// null,
        public string? shopPhoneNum{get;set;}// null,
        public string? customerAddress{get;set;}// null,
        public string? salesArea{get;set;}// null,
        public string? installType{get;set;}// null,
        public string? installServicer{get;set;}// null,
        public string? isTakeGoodsInstall{get;set;}// null,
        public string? installServicerName{get;set;}// null,
        public string? installDate{get;set;}// null,
        public int? deliveryCustomerId {get;set;}// 20338713,
        public string? deliveryGoodsStatus{get;set;}// "H",
        public string? receiveGoodsStatus{get;set;}// "H",
        public string? deliveryCustomerCode{get;set;}// "ORG-sjzb003",
        public string? deliveryCustomerName{get;set;}// "沧州市世纪厨具销售有限公司",
        public int? deliveryCustomerTypeId {get;set;}// 106,
        public string? deliveryCustomerTypeCode{get;set;}// "BSC-JXS",
        public string? deliveryCustomerTypeName{get;set;}// "办事处-经销商",
        public string? functionType{get;set;}// "PARTS_RETURN",
        public string? isUsingPolicy{get;set;}// "N",
        public int? userId {get;set;}// null,
        public string? superiorCustomerCode{get;set;}// null,
        public string? superiorCustomerName{get;set;}// null,
        public string? needErpFlag{get;set;}// "N",
        public string? province{get;set;}// null,
        public string? city{get;set;}// null,
        public string? countyDistrict{get;set;}// null,
        public string? street{get;set;}// null,
        public string? detailedAddress{get;set;}// null,
        public string? sourceDesc{get;set;}// "APP技师配件退回",
        public string? countryRegion{get;set;}// null,
        public string? province1{get;set;}// null,
        public string? city1{get;set;}// null,
        public string? countyDistrict1{get;set;}// null,
        public string? countryRegion1{get;set;}// null,
        public string? receiveAreaEditStatus{get;set;}// "B",
        public string? receiveAreaSource{get;set;}// "A",
        public string? priceEditFlag{get;set;}// "N",
        public string? isServiceMarket{get;set;}// null,
        public string? transportTypeName{get;set;}// "自提",
        public string? reservationDeliveryDate{get;set;}// null,
        public string? singlePerson{get;set;}// null,
        public string? singleDate{get;set;}// null,
        public string? fxOrderNo{get;set;}// null,
        public string? channelName{get;set;}// null,
        public int? channelId {get;set;}// null,
        public string? fxRemark{get;set;}// null,
        public List<CRM_PartsReturnDetail_crmSoOrderLineVs> crmSoOrderLineVs { get; set; }
    }

    public class CRM_PartsReturnDetail_crmSoOrderLineVs
    {
                public int? orderLineId{get;set;}// 37321963,
                public int? orderId {get;set;}// 34078302,
                public string? sourceType{get;set;}// null,
                public int? sourceId {get;set;}// 42804799,
                public int? sourceDetailId {get;set;}// null,
                public string? sourceCode{get;set;}// null,
                public string? sourceClassification{get;set;}// null,
                public string? orderLineNo{get;set;}// "1",
                public int? itemId {get;set;}// 1114329,
                public string? itemCode{get;set;}// "2010Y6B010000000F",
                public string? customerItemCode{get;set;}// null,
                public string? specificationModel{get;set;}// null,
                public string? orderUnit{get;set;}// "PCS",
                public int? orderQuantity {get;set;}// 1,
                public string? totalWeight{get;set;}// null,
                public string? weightUnit{get;set;}// null,
                public int? totalVolume {get;set;}// 0,
                public string? volumeExceedsTolerance{get;set;}// null,
                public string? volumeOwedTolerance{get;set;}// null,
                public string? deliveryTime{get;set;}// null,
                public string? aheadOfTolerance{get;set;}// null,
                public string? delayTolerance{get;set;}// null,
                public int? linePriceListId {get;set;}// null,
                public int? priceDiscountId {get;set;}// null,
                public int? price {get;set;}// 15,
                public string? lineDiscount{get;set;}// null,
                public string? price2{get;set;}// null,
                public string? compositeDiscount{get;set;}// null,
                public string? discountAmount{get;set;}// null,
                public string? taxRate{get;set;}// null,
                public string? taxAmount{get;set;}// null,
                public string? sumAmount{get;set;}// null,
                public string? lineRemark{get;set;}// "APP技师配件退回",
                public string? deliveryOrg{get;set;}// null,
                public int? deliveryWarehouse {get;set;}// 70280329,
                public string? inventoryCode{get;set;}// null,
                public string? deliveryWarehouseName{get;set;}// null,
                public string? warehouseLocation{get;set;}// null,
                public string? warehouseLocationName{get;set;}// null,
                public int? receiveInventoryId {get;set;}// 70252904,
                public string? receiveInventoryName{get;set;}// null,
                public int? receiveLocationId {get;set;}// null,
                public string? receiveLocationName{get;set;}// null,
                public string? latestOnhandQuantity{get;set;}// null,
                public string? latestReservedQuantity{get;set;}// null,
                public string? commitmentQuantity{get;set;}// null,
                public string? manufactureOrPurchaseDate{get;set;}// null,
                public string? finishInboundTime{get;set;}// null,
                public string? planArrivalTime{get;set;}// null,
                public string? planDeliveryTime{get;set;}// null,
                public int? itemTypeId {get;set;}// null,
                public int? netPrice {get;set;}// 15,
                public string? lineDiscount2{get;set;}// null,
                public string? discountAmount2{get;set;}// null,
                public string? weight{get;set;}// null,
                public int? referenceId {get;set;}// null,
                public int? referenceLineId {get;set;}// null,
                public string? productModelCode{get;set;}// null,
                public string? productModelSumCode{get;set;}// null,
                public string? isSampleSubsidy{get;set;}// "Y",
                public int? createdBy {get;set;}// 103,
                public string? creationDate{get;set;}// "2023-01-05",
                public int? lastUpdatedBy {get;set;}// 1,
                public string? lastUpdateDate{get;set;}// "2023-01-05",
                public string? realQuantity{get;set;}// null,
                public int? retainedQuantity {get;set;}// 1,
                public string? sorQty{get;set;}// null,
                public string? transQty{get;set;}// null,
                public int? approvalQty {get;set;}// 1,
                public string? rejectReason{get;set;}// null,
                public string? remark{get;set;}// null,
                public int? reserve3 {get;set;}// 1,
                public string? realRebate{get;set;}// null,
                public int? approveAmount {get;set;}// 15,
                public string? applyUseableAmount{get;set;}// null,
                public string? invoiceQty{get;set;}// null,
                public string? materialCode{get;set;}// "2010Y6B010000000F",
                public string? materialName{get;set;}// "液化石油气左铜芯配件(2)",
                public string? materialDesc{get;set;}// "液化石油气左铜芯配件(2)",
                public string? productStatus{get;set;}// null,
                public string? specification{get;set;}// null,
                public string? itemTypeName{get;set;}// null,
                public string? discountName{get;set;}// null,
                public string? priceName{get;set;}// null,
                public string? haveBom{get;set;}// null,
                public string? markCategory{get;set;}// null,
                public string? orderedModel{get;set;}// null,
                public string? deliveryOrgName{get;set;}// null,
                public string? status{get;set;}// null,
                public string? deliveryFreeze{get;set;}// null,
                public string? invoiceFreeze{get;set;}// null,
                public string? emergencyDegree{get;set;}// null,
                public string? isDeferred{get;set;}// null,
                public string? isReturn{get;set;}// null,
                public string? returnQty{get;set;}// null,
                public string? returnReason{get;set;}// null,
                public string? haveArrears{get;set;}// null,
                public string? wholeSingleDelivery{get;set;}// null,
                public int? lineStatusId {get;set;}// null,
                public string? isPartialShipment{get;set;}// null,
                public string? isDeliveryed{get;set;}// null,
                public string? isMakedInvoice{get;set;}// null,
                public string? isReceivedCash{get;set;}// null,
                public int? freezeDeforstId {get;set;}// null,
                public string? returnReasonsName{get;set;}// null,
                public string? applyNo{get;set;}// null,
                public string? applyTitle{get;set;}// null,
                public string? unsalableQty{get;set;}// null,
                public string? approvalInfo{get;set;}// "第一审批人: 数量：\n第二审批人: 数量：\n 第三审批人: 数量：\n第四审批人: 数量：\n 第五审批人: 数量：",
                public string? referenceInfo{get;set;}// null,
                public string? offsiteInvQty{get;set;}// null,
                public string? appNotExQty{get;set;}// null,
                public string? baseInvQty{get;set;}// null,
                public int? foreProduceQty {get;set;}// 0,
                public string? releaseQty{get;set;}// null,
                public string? headquartersPrice{get;set;}// null,
                public string? branchPrice{get;set;}// null,
                public string? lineType{get;set;}// null,
                public string? isEditFlag{get;set;}// null,
                public string? isGift{get;set;}// null,
                public string? itemAttribute{get;set;}// null,
                public string? parentItemNo{get;set;}// null,
                public string? subItemRatio{get;set;}// null,
                public string? boxNum{get;set;}// null,
                public string? verificationQty{get;set;}// null,
                public string? canVerificationQty{get;set;}// null,
                public int? goodsPoolId {get;set;}// null,
                public string? deliverQtyOfBlue{get;set;}// null,
                public int? blueOrderLineId {get;set;}// null,
                public int? pSourceId {get;set;}// null,
                public string? orderPrice{get;set;}// null,
                public string? goodsPoolId1{get;set;}// null,
                public string? sendQuotaRatio{get;set;}// null,
                public string? balancePoolType1{get;set;}// null,
                public string? balancePoolType2{get;set;}// null,
                public string? balancePoolType3{get;set;}// null,
                public string? balancePoolType4{get;set;}// null,
                public string? balancePoolType5{get;set;}// null,
                public string? balancePoolType6{get;set;}// null,
                public string? balancePoolType7{get;set;}// null,
                public string? balancePoolType8{get;set;}// null,
                public string? balancePoolType9{get;set;}// null,
                public string? balancePoolType10{get;set;}// null,
                public string? balancePoolRatio1{get;set;}// null,
                public string? balancePoolRatio2{get;set;}// null,
                public string? balancePoolRatio3{get;set;}// null,
                public string? balancePoolRatio4{get;set;}// null,
                public string? balancePoolRatio5{get;set;}// null,
                public string? balancePoolRatio6{get;set;}// null,
                public string? balancePoolRatio7{get;set;}// null,
                public string? balancePoolRatio8{get;set;}// null,
                public string? balancePoolRatio9{get;set;}// null,
                public string? balancePoolRatio10{get;set;}// null,
                public string? maxPolicyQty{get;set;}// null,
                public string? settlementPrice{get;set;}// null,
                public string? contractQty{get;set;}// null,
                public string? fanName{get;set;}// null,
                public string? equipmentCode{get;set;}// null,
                public string? electricMachine{get;set;}// null,
                public string? description{get;set;}// null,
                public string? blastCapacity{get;set;}// null,
                public string? allPressure{get;set;}// null,
                public string? voltage{get;set;}// null,
                public string? rotateSpeed{get;set;}// null,
                public string? isCreateCertificate{get;set;}// null,
                public string? itemName{get;set;}// "液化石油气左铜芯配件(2)",
                public string? deliverDoodsTime{get;set;}// null,
                public string? power{get;set;}// null,
                public string? isChange{get;set;}// null,
                public string? noise{get;set;}// null,
                public string? windType{get;set;}// null,
                public string? preSendDate{get;set;}// null,
                public string? rebateAmount{get;set;}// null,
                public string? rebateDiscount{get;set;}// null,
                public string? rebatedPrice{get;set;}// null,
                public string? rebatedAmount{get;set;}// null,
                public string? color{get;set;}// null,
                public string? closeFlag{get;set;}// null,
                public string? fullName{get;set;}// null,
                public string? courierNumber{get;set;}// null,
                public string? buyerRemark{get;set;}// null,
                public string? address{get;set;}// null,
                public string? phoneNum{get;set;}// null,
                public string? collectDate{get;set;}// null,
                public string? ecOrderNum{get;set;}// null,
                public string? installType{get;set;}// null,
                public string? installServicer{get;set;}// null,
                public string? isTakeGoodsInstall{get;set;}// null,
                public string? installDate{get;set;}// null,
                public string? deliveryGoodsStatus{get;set;}// "H",
                public string? receiveGoodsStatus{get;set;}// "H",
                public string? volumeUnit{get;set;}// "M3",
                public int? volume {get;set;}// 0,
                public string? requestHNumber{get;set;}// null,
                public string? requestLNumber{get;set;}// null,
                public string? headNo{get;set;}// null,
                public string? lineNo{get;set;}// null,
                public string? deliveryGoodsStatusName{get;set;}// "新料",
                public int? invQuantity {get;set;}// 1,
                public string? orderNum{get;set;}// "JSTH202301050289",
                public int? byNo {get;set;}// 1
    }
}
